import os
import re
import math
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)
app.config['JSON_SORT_KEYS'] = False

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

LOG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'audit_log.json')

def read_logs():
    if not os.path.exists(LOG_FILE):
        return []
    try:
        with open(LOG_FILE, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            if not content:
                return []
            return json.loads(content)
    except Exception:
        return []

def write_log(entry):
    logs = read_logs()
    logs.append(entry)
    try:
        with open(LOG_FILE, 'w', encoding='utf-8') as f:
            json.dump(logs, f, indent=2)
    except Exception as e:
        app.logger.error(f"Failed to write to log file: {e}")

def update_log_status_and_appeal(submission_id, appeal_obj):
    logs = read_logs()
    found = False
    for entry in logs:
        if entry.get("content_id") == submission_id or entry.get("submission_id") == submission_id:
            entry["status"] = "under_review"
            entry["appeal"] = appeal_obj
            found = True
            break
    if found:
        try:
            with open(LOG_FILE, 'w', encoding='utf-8') as f:
                json.dump(logs, f, indent=2)
            return True
        except Exception as e:
            app.logger.error(f"Failed to update log file: {e}")
            return False
    return False

def calculate_linguistic_complexity(text):
    """
    Computes local linguistic complexity based on sentence length variance (burstiness)
    and Type-Token Ratio (TTR - lexical density).
    Returns a score S2 in [0.0, 1.0].
    - 1.0 represents extreme uniformity (low sentence length variance, highly repetitive vocabulary).
    - 0.0 represents highly variable sentence structures and diverse vocabulary.
    """
    if not text or not text.strip():
        return 1.0

    sentence_delimiters = re.compile(r'[.!?]+')
    raw_sentences = sentence_delimiters.split(text)
    
    sentence_lengths = []
    all_words = []
    
    for s in raw_sentences:
        s_clean = s.strip()
        if not s_clean:
            continue
        words = [re.sub(r'[^\w\s]', '', w).lower() for w in s_clean.split()]
        words = [w for w in words if w]
        if words:
            sentence_lengths.append(len(words))
            all_words.extend(words)
            
    if not all_words:
        return 1.0
        
    total_tokens = len(all_words)
    unique_tokens = len(set(all_words))
    ttr = unique_tokens / total_tokens if total_tokens > 0 else 0.0
    
    num_sentences = len(sentence_lengths)
    if num_sentences > 1:
        mean_len = sum(sentence_lengths) / num_sentences
        variance = sum((x - mean_len) ** 2 for x in sentence_lengths) / num_sentences
    else:
        variance = 0.0
        
    s_var = math.exp(-variance / 20.0)
    
    s_ttr = 1.0 - ttr
    
    s2 = 0.5 * s_var + 0.5 * s_ttr
    
    return max(0.0, min(1.0, s2))

def calculate_llm_stylistic_probability(text):
    """
    Sends the text to the Groq API using llama-3.3-70b-versatile with a structured prompt.
    Returns a score S1 in [0.0, 1.0] representing the probability that the text is AI-generated.
    Falls back to None on failure to ensure system resilience.
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print("Groq API key not found in environment.")
        return None

    try:
        client = Groq(api_key=api_key)
        
        system_prompt = (
            "You are an expert stylometrist analyzing text to determine if it was generated by an AI language model. "
            "Evaluate token predictability, sentence length variation patterns, paragraph transitions, "
            "and characteristic AI terms (e.g., 'delve', 'testament', 'tapestry', 'furthermore', 'monumental', 'crucial'). "
            "Respond ONLY with a valid JSON object containing a single key 'ai_probability' which is a float "
            "between 0.0 and 1.0 (where 1.0 is definitely AI-generated and 0.0 is definitely human-authored). "
            "Do not include any explanation or markdown formatting other than JSON."
        )
        
        user_prompt = f"Analyze the following text:\n\n{text}"
        
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            model="llama-3.3-70b-versatile",
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        
        content = chat_completion.choices[0].message.content
        res = json.loads(content)
        prob = float(res.get("ai_probability", 0.5))
        return max(0.0, min(1.0, prob))
    except Exception as e:
        print(f"Groq API error: {e}")
        return None

def combine_signals_and_calibrate(s1, s2):
    """
    Combines Signal 1 (Groq LLM Probability, w1 = 0.6) and Signal 2 (Local Complexity, w2 = 0.4).
    If Signal 1 is not available (None), falls back entirely to Signal 2.
    
    Returns:
      - p_ai: Combined probability score in [0.0, 1.0]
      - attribution: Class label ('likely_human', 'likely_ai', or 'uncertain')
      - confidence: Calibrated confidence score in [0.0, 1.0]
    """
    if s1 is None:
        p_ai = s2
    else:
        p_ai = 0.6 * s1 + 0.4 * s2
        
    p_ai = max(0.0, min(1.0, p_ai))
    
    if p_ai >= 0.80:
        attribution = "likely_ai"
        confidence = p_ai
    elif p_ai <= 0.20:
        attribution = "likely_human"
        confidence = 1.0 - p_ai
    else:
        attribution = "uncertain"
        confidence = 1.0 - (abs(p_ai - 0.50) / 0.30)
        confidence = max(0.0, min(1.0, confidence))
        
    return p_ai, attribution, confidence

@app.route("/")
def home():
    return "Provenance Guard is running."

@app.route("/submit", methods=["POST"])
@app.route("/api/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json() or {}
    text = data.get('text') or data.get('content') or ""
    creator_id = data.get('creator_id', 'anonymous')
    
    if not text:
        return jsonify({"error": "Missing required field 'text' or 'content'"}), 400

    s1 = calculate_llm_stylistic_probability(text)
    s2 = calculate_linguistic_complexity(text)
    
    p_ai, attribution, confidence = combine_signals_and_calibrate(s1, s2)
    
    conf_pct = int(round(confidence * 100))
    if attribution == "likely_ai":
        label = f"AI-Generated: Our analysis indicates with high confidence ({conf_pct}% similarity to machine patterns) that this content was generated by an AI system. It exhibits highly predictable patterns, uniform sentence lengths, and stylistic markers characteristic of machine-generated text."
    elif attribution == "likely_human":
        label = f"Verified Human: Our analysis indicates with high confidence ({conf_pct}% similarity to human patterns) that this content was authored by a human. It shows natural linguistic variation and complex sentence structures typical of human creativity."
    else:
        label = f"Mixed or Uncertain: Our analysis is unable to definitively attribute this content (uncertainty index {conf_pct}%). It exhibits a blend of natural human style and structured machine patterns. This could indicate human text that has been heavily AI-edited, or AI text designed to mimic human writing."

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    
    log_entry = {
      "content_id": content_id,
      "submission_id": content_id,
      "creator_id": creator_id,
      "timestamp": timestamp,
      "attribution": attribution,
      "confidence": round(confidence, 2),
      "llm_score": round(s1, 2) if s1 is not None else None,
      "signals": {
          "local_complexity": round(s2, 2),
          "llm_stylistic": round(s1, 2) if s1 is not None else None
      },
      "label": label,
      "status": "classified",
      "appeal": None
    }
    
    write_log(log_entry)
    
    return jsonify({
        "content_id": content_id,
        "submission_id": content_id,
        "attribution": attribution,
        "confidence": round(confidence, 2),
        "label": label,
        "signals": {
            "local_complexity": round(s2, 2),
            "llm_stylistic": round(s1, 2) if s1 is not None else None
        },
        "status": "classified",
        "created_at": timestamp
    }), 200

@app.route("/appeal", methods=["POST"])
@app.route("/api/appeal", methods=["POST"])
def appeal():
    data = request.get_json() or {}
    submission_id = data.get("content_id") or data.get("submission_id")
    reasoning = data.get("creator_reasoning") or data.get("reasoning")
    
    if not submission_id or not reasoning:
        return jsonify({"error": "Missing required field 'content_id' or 'creator_reasoning'"}), 400
        
    if len(reasoning) < 10:
        return jsonify({"error": "Reasoning must be at least 10 characters long"}), 400
        
    appeal_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    
    appeal_obj = {
        "appeal_id": appeal_id,
        "reasoning": reasoning,
        "creator_reasoning": reasoning,
        "created_at": timestamp
    }
    
    success = update_log_status_and_appeal(submission_id, appeal_obj)
    if not success:
        return jsonify({"error": f"Submission with ID {submission_id} not found"}), 404
        
    return jsonify({
        "appeal_id": appeal_id,
        "submission_id": submission_id,
        "content_id": submission_id,
        "status": "under_review",
        "reasoning": reasoning,
        "created_at": timestamp
    }), 200

@app.route("/log", methods=["GET"])
@app.route("/api/log", methods=["GET"])
def get_log():
    logs = read_logs()
    return jsonify({
        "entries": logs,
        "logs": logs
    }), 200

if __name__ == "__main__":
    app.run(port=5000, debug=True)